CREATE TABLE Team(
	ID INT IDENTITY (1,1) NOT NULL,
	Name NVARCHAR(50),
	CONSTRAINT pk_teamID PRIMARY KEY (ID)
	);

	CREATE TABLE MatchSchedule(
		ID INT IDENTITY (500,1) NOT NULL,
		HomeTeamID INT,
		GuestTeamID INT,
		MatchDAte DATETIME2,
		CONSTRAINT pk_scheduleID PRIMARY KEY (ID),
		CONSTRAINT fk_gtID FOREIGN KEY (GuestTeamID) REFERENCES Team(ID),
		CONSTRAINT fk_htID FOREIGN KEY (HomeTeamID) REFERENCES Team(ID)
	);